### ISSUE TITLE
Switch to a different license than Modelica License 2

### ISSUE THREAD

**Issue by dietmarw** [MarekMatejak/Chemical#10]
It might be advisable to NOT use the Modelica Licence 2 since that one is not really suitable for anything other than the Modelica Standard Library. Have a read through https://github.com/xogeny/impact/blob/master/resources/docs/modelica2015/paper/impact.md#which-license-is-best-for-your-library and decide for yourself.

**Comment by dietmarw** [comment]
What is the resolution?

**Comment by MarekMatejak** [comment]
We decided to use Modelica License 2.0 for next release 1.1.0. May be, the Chemical library could be the  part of MSL. Do you know where and how to make this proposal?

**Comment by dietmarw** [comment]
There is no necessity to have it under ML 2.0 in order to make it part of the MSL. BSD license is just as well compatible with the ML 2.0 and allows legal forking and PR (something that ML 2.0 strictly speaky not allows). You should contact the design list modelica-design@modelica.org about your proposal. It will then be put up for discussion at some point.

**Comment by MarekMatejak** [comment]
Done. We changed the license to BSD 3-Clause. Thank you

**Comment by tbeu** [comment]
:+1:

**Comment by dietmarw** [comment]
:+1:
