### ISSUE TITLE
crowdfunding

### ISSUE THREAD

**Issue by thorade** [MarekMatejak/Chemical#15]
The link in the Readme is broken.
This one works:
http://igg.me/at/mephysmo

**Comment by MarekMatejak** [comment]
Thank you Matthis.

**Comment by tbeu** [comment]
Do you intend to announce the crowdfunding in the Mo community? Maybe a mail to the design list can help to spread the goal.

**Comment by tbeu** [comment]
BTW it was discussed if the Modelica Conference 2017 could take place in Praha.

**Comment by MarekMatejak** [comment]
Really? :-) Let us know if you want some help with organization. For example we have a good experience with Action-M ( http://www.action-m.com ) in organization of conferences and making of proceedings.

**Comment by tbeu** [comment]
I can't do anything about it and do not know what happens within MA board or other channels. Just wanted to let you know about it.
![12moco](https://cloud.githubusercontent.com/assets/5444067/10290459/83b2097e-6ba4-11e5-9605-d7dbcc273003.png)
If you are an MA member you can read full meeting notes here: https://trac.modelica.org/Modelica/browser/ModelicaDesign/trunk/MeetingMinutesMaterial/min87_2015_Paris/min87.pdf

**Comment by tbeu** [comment]
Just in case you did not receive that one.

> Von: modelica-design@googlegroups.com [mailto:modelica-design@googlegroups.com] Im Auftrag von Martin Otter
Gesendet: Montag, 1. Februar 2016 16:28
An: Modelica-design@Modelica.org
Betreff: [MD] Next Modelica Conference 2017 - Local Organizer?

> Dear Modelicans,
at the Modelica Design Meeting in Paris (Sept. 2015), it was discussed to have the next Modelica Conference in
March 2017
We have discussed possible locations and local organizers but no conclusion was made.
It is now urgent to fix local organizer, location, and date of the next conference.
Please, send an email if you are interested to organize the next Modelica conference.
Best regards,

> Martin 
--------------------------------------------------------------------------
Prof. Dr.-Ing. Martin Otter, Vice director DLR-SR
Deutsches Zentrum für Luft- und Raumfahrt e.V. (DLR)
Robotik und Mechatronik Zentrum
Institut für Systemdynamik und Regelungstechnik (DLR-SR)
Forschungszentrum Oberpfaffenhofen
D-82234 Wessling
Germany

**Comment by thorade** [comment]
Closing some old issues.
Also see:
https://modelica.org/events/modelica2017
http://modelica.cz/
