### ISSUE TITLE
OpenModelica 1.9.2 cannot simulate some of examples

### ISSUE THREAD

**Issue by filip-jezek** [MarekMatejak/Chemical#6]
In model i.e. LeadAcidBattery, there is a problem with string array References - expected References [1], but had References [2]. Thus refuses to even translate and simulate.

Dymola works fine.

**Comment by MarekMatejak** [comment]
Ahoj Filipe,
uspesne som dokoncil a odladil som ten FluidAdapter, cim by malo byt mozne
prepojenie so standardnymi komponentami v MSL 3.2 baliku Modelica.Fluid.
Jak mas cas, tak skus prosim Ta tie ukazky (Chemical.Examples.FluidAdapter
a vlastne aj vsetky ostane - pretoze som menil i komponentu Solution i
vypocet enthalpie idealneho plynu) otestovat v OpenModelice.
Dik.
Zatim
M.

2015-06-19 12:04 GMT+02:00 Filip Ježek <notifications@github.com>:

**Comment by filip-jezek** [comment]
Generally, I would propose noting some variables in documentation, which we should look at - there is a bunch of values and conditions. 

With OpenModelica 1.9.3, Nightly-build. Branch Master.

**Examples.SimpleReaction** - (nearly each model has this warning):
assert | warning | <p>The following assertion has been violated at time 0.002000<br>
H2O.solution.m &gt;= 0.0 and H2O.solution.m &lt;= 0.0</p>
assert | warning | 

**Examples.PowerGeneration Fails** - nonlinear system failed at T cca 2.86e-6s
assert | debug | <p>Division by zero T / p</p>
assert | debug | <p>Solving non-linear system 182 failed at time=2.86251740229245e-006.<br>
For more information please use -lv LOG_NLS.</p>

Seems to have something in common also with previous problem:
stdout | warning | <p>A Modelica assert prevents the integrator to continue. For more information use -lv LOG_SOLVER</p>
stdout | warning | <p>can't continue. time = 0.000003</p>
assert | warning | <p>The following assertion has been violated at time 0.000003<br>
H2O_gas.solution.n &gt;= 0.0 and H2O_gas.solution.n &lt;= 0.0</p>

**Examples.EnzymeKinetics** Fails (ES.x hits zero approx 200s before dymola does) - reduce the simulation time

**Examples.LeadAcidBattery** Fails in compilation

Chemical.Examples.LeadAcidBattery_03lsy.c: In function 'Chemical_Examples_LeadAcidBattery_initialLinearSystem':
Chemical.Examples.LeadAcidBattery_03lsy.c:857: error: 'Chemical_Examples_LeadAcidBattery_functionJacNLSJac5_column' undeclared (first use in this function)
Chemical.Examples.LeadAcidBattery_03lsy.c:857: error: (Each undeclared identifier is reported only once
Chemical.Examples.LeadAcidBattery_03lsy.c:857: error: for each function it appears in.)
Chemical.Examples.LeadAcidBattery_03lsy.c:858: error: 'Chemical_Examples_LeadAcidBattery_initialAnalyticJacobianNLSJac5' undeclared (first use in this function)
...
Compilation process failed. Exited with code 2.

**Red Cell membrane** works, but does not make any sense.
